### ISSUE TITLE
Open fails on some interprets because of encoding

### ISSUE THREAD

**Issue by jmmelko** [sky-music/sky-python-music-sheet-maker#29]
Not specifying the encoding provokes a UnicodeDecodeError with some interpreters.

I think we should open assuming utf-8 (since Sky is a japanese game, using Latin-1 would be an insult), ignoring errors.

The same for writing.

**Comment by t1-tracey** [comment]
Yep utf-8 sounds good

Sent from my iPad

On 25 Nov 2019, at 5:06 am, jmmelko <notifications@github.com> wrote:

﻿

Not specifying the encoding provokes a UnicodeDecodeError with some interpreters.

I think we should open assuming utf-8 (since Sky is a japanese game, using Latin-1 would be an insult), ignoring errors.

The same for writing.

**Comment by jmmelko** [comment]
Fixed in beta, waiting for acknowledgement of pull request.
