### ISSUE TITLE
Support for Asian characters

### ISSUE THREAD

**Issue by jmmelko** [sky-music/sky-python-music-sheet-maker#36]
The roboto font used for rendering PNGs does not handle Asian characters.
=> download and use Google Noto font:

https://www.google.com/get/noto/help/cjk/

I don’t know if they support  flat and sharp. In the meantime they can replaced by 'b' and the sharp by '#'.

I also have to check how Asian characters are rendered in HTML and SVG, which use style sheets.

**Comment by jmmelko** [comment]
I have changed the beta to use a Goole/Adobe Noto font which support all asian characters (CJK means Chinese+Japanese+Korean), except some language-specific variants.

Can someone tell me if Asian and special characters are now correctly rendered in the PNG now? 

Also, japanese characters are correctly rendered in HTML and SVG even without referring to the font. I suppose this is because the browser looks up for the appropriate in the system of each user. This is why I added some lines in the CSS to suggest the browser to use the Noto font, but withut the "import" module that would force the browser to download the font each time.

**Comment by t1-tracey** [comment]
Sure I can test this quickly in a bit.

Sent from my iPad

On 30 Nov 2019, at 7:37 am, jmmelko <notifications@github.com> wrote:

﻿

I have changed the beta to use a Goole/Adobe Noto font which support all asian characters (CJK means Chinese+Japanese+Korean), except some language-specific variants.

Can someone tell me if Asian and special characters are now correctly rendered in the PNG now?

Also, japanese characters are correctly rendered in HTML and SVG even without referring to the font. I suppose this is because the browser looks up for the appropriate in the system of each user. This is why I added some lines in the CSS to suggest the browser to use the Noto font, but withut the "import" module that would force the browser to download the font each time.

**Comment by t1-tracey** [comment]
works great!

![トレーシーの音楽](https://user-images.githubusercontent.com/22441348/69893586-b821bf00-1367-11ea-90dd-08c51a2dc3df.png)
![トレーシーの音楽1](https://user-images.githubusercontent.com/22441348/69893587-b821bf00-1367-11ea-88da-af8de4f0ba76.png)

**Comment by jmmelko** [comment]
Ok I’ll close that for now, until some one complains, perhaps, one day.
