### ISSUE TITLE
There is a confusion between missing chords and pauses (breaks)

### ISSUE THREAD

**Issue by jmmelko** [sky-music/sky-python-music-sheet-maker#8]
Pauses and missing chords are output the same way: a big grey button.
We should have the choice.

**Comment by t1-tracey** [comment]
yeah they were output in the same way^ I wasn't sure how to handle the error (output the error in the command line), I guess a red cross for errors might work too - but I do agree with handling the error rather than outputting it as a pause :+1:

for the breaks/rests, originally I had empty tables. it seemed kind of cluttered to me, so that's why I changed it to a single grey dot. here is what they used to look like for reference, though:

first version:
https://sky-music.github.io/songs/threshold-bass.html
<img width="845" alt="screenshot of threshold transcript in sky sheet music form" src="https://user-images.githubusercontent.com/22441348/67994271-759d9180-fc98-11e9-8ced-728fa374dc00.png">

second version:
https://sky-music.github.io/songs/journey-theme.html
<img width="596" alt="screenshot of journey theme transcript in sky sheet music form" src="https://user-images.githubusercontent.com/22441348/67994305-aa114d80-fc98-11e9-8252-ce45cc66d2dc.png">

I hadn't tried a white gap yet or a pause symbol, feel free to :D

**Comment by jmmelko** [comment]
solved in beta.
